### ISSUE TITLE
Use specialised stores without mask in calc_loop_of_clusters

### ISSUE THREAD

**Issue by christiealappatt** [intel/yask#244] opened 2020-04-15 10:48 UTC
Currently to write back a vector, YASK compiler uses the general 'storeTo_masked' routine. However in the main loop (calc_loop_of_clusters) it could use the 'storeTo' routine instead (write_mask is -1). 

This has a performance advantage on AVX/AVX2 machine because the conditional jump inside the innermost loop due to 'storeTo_masked' routine can be avoided. In some cases the performance advantage was more than 15%  on AMD ROME.

As an easy fix the 'storeTo' routine can be called inside the 'storeTo_masked' routine (defined in src/kernel/lib/realv.hpp.) if the mask=-1.

**Comment by chuckyount** [comment] 2020-04-15 17:01
Thanks for the feedback and the detailed issue. The call to `storeTo_masked` was left in `calc_loop_of_clusters` because the Intel C++ compiler recognizes when a constant "all-ones" (from `constexpr idx_t write_mask = idx_t (-1);`) mask is used in `calc_loop_of_clusters`, and it automatically replaces the masked store with a regular store (i.e., `vmovups`), at least for avx512. I have confirmed that this optimization is not applied for avx2. This is likely because the int mask has to be transformed into a ymm mask (`realv.hpp line 491), and the compiler doesn't recognize this idiom. It would not be advisable to put a run-time conditional test inside `storeTo_masked`, because branches also have a large negative impact on performance. The better solution would be for the YASK compiler to generate `storeTo` instead of `storeTo_masked` directly inside `calc_loop_of_clusters`. I will investigate this enhancement, but feel free to fork the repo and submit a pull request.

**Comment by chuckyount** [comment] 2020-04-15 21:12
A fix has been pushed to the `develop` branch if you want to test it.

**Comment by christiealappatt** [comment] 2020-04-16 07:47
Thanks a lot for the quick action. I tested the fix, it works :)

**Closed** 2020-04-16 16:14 UTC
Labels: enhancement
